name: Publish annotation processor

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
    paths:
      - annotation-processor/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Configure maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./configure-maven.sh ${GITHUB_TOKEN} ${GITHUB_REPOSITORY}
    - name: Publish annotation processor
      run: |
        cd $GITHUB_WORKSPACE/annotation-processor
        mvn deploy
