name: Publish sdk

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
    paths:
      - addonssdk/**

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Configure maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./configure-maven.sh ${GITHUB_TOKEN} ${GITHUB_REPOSITORY}
    - name: Run SDK publishing script
      run: |
        cd $GITHUB_WORKSPACE/addonssdk
        ./publish.sh ${{ secrets.GITHUB_TOKEN }} "${{ toJson(github.event.pull_request.labels.*.name) }}"
